PracBundle/Entity/Citizen.php
<?php

namespace CpuSeDept\PracBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Citizen
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="CpuSeDept\PracBundle\Entity\CitizenRepository")
 */
class Citizen
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstName", type="string", length=255)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="lastName", type="string", length=255)
     */
    private $lastName;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birthdate", type="date")
     */
    private $birthdate;

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", length=6)
     */
    private $gender;

    /**
     * @var string
     *
     * @ORM\Column(name="disability", type="string", length=255)
     */
    private $disability;

    /**
     * @var Town
     * @ORM\ManyToOne(targetEntity="Town", inversedBy="citizens")
     */
    private $hometown;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Citizen
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string 
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return Citizen
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string 
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set birthdate
     *
     * @param \DateTime $birthdate
     * @return Citizen
     */
    public function setBirthdate($birthdate)
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    /**
     * Get birthdate
     *
     * @return \DateTime 
     */
    public function getBirthdate()
    {
        return $this->birthdate;
    }

    /**
     * Set gender
     *
     * @param string $gender
     * @return Citizen
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return string 
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Set disability
     *
     * @param string $disability
     * @return Citizen
     */
    public function setDisability($disability)
    {
        $this->disability = $disability;

        return $this;
    }

    /**
     * Get disability
     *
     * @return string 
     */
    public function getDisability()
    {
        return $this->disability;
    }

    /**
     * Set hometown
     *
     * @param \CpuSeDept\PracBundle\Entity\Town $hometown
     * @return Citizen
     */
    public function setHometown(\CpuSeDept\PracBundle\Entity\Town $hometown = null)
    {
        $this->hometown = $hometown;

        return $this;
    }

    /**
     * Get hometown
     *
     * @return \CpuSeDept\PracBundle\Entity\Town 
     */
    public function getHometown()
    {
        return $this->hometown;
    }
    
    public function isDisabled()
    {
        return $this->disability != "";
    }
    
    public function getAge()
    {
        $now = new \DateTime();
        return $now->diff($this->birthdate)->y;
    }
    
    public function isSenior() {
        return $this->getAge() >= 65;
    }
    
    public function isChild() {
        return $this->getAge() <= 12;
    }
}

PracBundle/Entity/Town.php
<?php

namespace CpuSeDept\PracBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Town
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="CpuSeDept\PracBundle\Entity\TownRepository")
 */
class Town
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="province", type="string", length=255)
     */
    private $province;

    /**
     * @var Citizen
     * @ORM\OneToOne(targetEntity="Citizen")
     */
    private $mayor;
    
    /**
     * @var Citizen[]
     * @ORM\OneToMany(targetEntity="Citizen", mappedBy="hometown")
     */
    private $citizens;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Town
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set province
     *
     * @param string $province
     * @return Town
     */
    public function setProvince($province)
    {
        $this->province = $province;

        return $this;
    }

    /**
     * Get province
     *
     * @return string 
     */
    public function getProvince()
    {
        return $this->province;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->citizens = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set mayor
     *
     * @param \CpuSeDept\PracBundle\Entity\Citizen $mayor
     * @return Town
     */
    public function setMayor(\CpuSeDept\PracBundle\Entity\Citizen $mayor = null)
    {
        $this->mayor = $mayor;

        return $this;
    }

    /**
     * Get mayor
     *
     * @return \CpuSeDept\PracBundle\Entity\Citizen 
     */
    public function getMayor()
    {
        return $this->mayor;
    }

    /**
     * Add citizens
     *
     * @param \CpuSeDept\PracBundle\Entity\Citizen $citizens
     * @return Town
     */
    public function addCitizen(\CpuSeDept\PracBundle\Entity\Citizen $citizens)
    {
        $this->citizens[] = $citizens;

        return $this;
    }

    /**
     * Remove citizens
     *
     * @param \CpuSeDept\PracBundle\Entity\Citizen $citizens
     */
    public function removeCitizen(\CpuSeDept\PracBundle\Entity\Citizen $citizens)
    {
        $this->citizens->removeElement($citizens);
    }

    /**
     * Get citizens
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCitizens()
    {
        return $this->citizens;
    }
}

PracBundle/Controller/TownController.php
<?php

namespace CpuSeDept\PracBundle\Controller;

use CpuSeDept\PracBundle\Entity\TownRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/town")
 */
class TownController extends Controller
{
    /**
     * @Route( "/evacuate/{id}" )
     * @Template
     */
    public function evacuateAction($id) 
    {
        $repo = $this->getDoctrine()->getRepository("CpuSeDeptPracBundle:Town");
        /* @var $repo TownRepository */
        return ['evacuees' => $repo->findWomenAndChildrenFromTown($id) ];
    }
    
    /**
     * @Route( "/list-seniors/{id}" )
     * @Template
     */
    public function listSeniorsAction($id) 
    {
        $repo = $this->getDoctrine()->getRepository("CpuSeDeptPracBundle:Town");
        /* @var $repo TownRepository */
        return ['seniors' => $repo->findElderlyFromTown($id) ];
    }
    
    /**
     * @Route( "/find-town" )
     * @Route( "/" )
     * @Template
     */
    public function findTownAction(Request $request) 
    {
        $repo = $this->getDoctrine()->getRepository("CpuSeDeptPracBundle:Town");
        /* @var $repo TownRepository */
        $q = $request->query->get('q') ?: '';
        return ['matches' => $repo->findTownLikeName($q) ];
    }
    
     /**
     * @Route( "/view/{id}" )
     * @Template
     */
    public function viewAction($id) 
    {
        $repo = $this->getDoctrine()->getRepository("CpuSeDeptPracBundle:Town");
        /* @var $repo TownRepository */
        return ['town' => $repo->find($id) ];
    }
    
     /**
     * @Route( "/list-pwds/{id}" )
     * @Template
     */
    public function listPwdsAction($id) 
    {
        $repo = $this->getDoctrine()->getRepository("CpuSeDeptPracBundle:Citizen");
        /* @var $repo TownRepository */
        return ['citizens' => $repo->findByHometown($id) ];
    }
}

PracBundle/Resources/views/Town/evacuate.html.twig
<html>
    <head>
        <title>title</title>
    </head>
    <body>
        <div id="header" style="border-bottom: 1px solid blue; padding: 8px;">
            <h1>SfCensus</h1>
            
            <form action="/prac/web/app_dev.php/town/find-town" method="get">
                <input type="search" name="q" />
                <button type="submit">SEARCH</button>
            </form>
        </div>
        
        <div id="content">
            <ol>
            {% for e in evacuees %}
                <li>
                    {{ e.lastName }}, {{ e.firstName }} ({{e.age}}/{{e.gender}})
                </li>
            {% endfor %}
            </ol>
        </div>
    </body>
</html>

PracBundle/Resources/views/Town/findTown.html.twig
<html>
    <head>
        <title>title</title>
    </head>
    <body>
        <div id="header" style="border-bottom: 1px solid blue; padding: 8px;">
            <h1>SfCensus</h1>
            
            <form action="/prac/web/app_dev.php/town/find-town" method="get">
                <input type="search" name="q" />
                <button type="submit">SEARCH</button>
            </form>
        </div>
        
        <div id="content">
            <ol>
            {% for t in matches %}
                <li>
                    <a href="/prac/web/app_dev.php/town/view/{{t.id}}">
                        {{t.name}}, {{t.province}}
                    </a>
                </li>
            {% endfor %}
            </ol>
        </div>
    </body>
</html>

PracBundle/Resources/views/Town/listPwds.html.twig
<html>
    <head>
        <title>title</title>
    </head>
    <body>
        <div id="header" style="border-bottom: 1px solid blue; padding: 8px;">
            <h1>SfCensus</h1>
            
            <form action="/prac/web/app_dev.php/town/find-town" method="get">
                <input type="search" name="q" />
                <button type="submit">SEARCH</button>
            </form>
        </div>
        
        <div id="content">
            <ol>
            {% for c in citizens %}                
                {% if c.disabled %}
                    <li>
                        {{ c.lastName }}, {{ c.firstName }} ({{c.disability}})
                    </li>
                {% endif %}
            {% endfor %}
            </ol>
        </div>
    </body>
</html>

PracBundle/Resources/views/Town/listSeniors.html.twig
<html>
    <head>
        <title>title</title>
    </head>
    <body>
        <div id="header" style="border-bottom: 1px solid blue; padding: 8px;">
            <h1>SfCensus</h1>
            
            <form action="/prac/web/app_dev.php/town/find-town" method="get">
                <input type="search" name="q" />
                <button type="submit">SEARCH</button>
            </form>
        </div>
        
        <div id="content">
            <ol>
            {% for s in seniors %}
                <li>
                    {{ s.lastName }}, {{ s.firstName }} ({{s.age}}/{{s.gender}})
                </li>
            {% endfor %}
            </ol>
        </div>
    </body>
</html>

PracBundle/Resources/views/Town/view.html.twig
<html>
    <head>
        <title>title</title>
    </head>
    <body>
        <div id="header" style="border-bottom: 1px solid blue; padding: 8px;">
            <h1>SfCensus</h1>
            
            <form action="/prac/web/app_dev.php/town/find-town" method="get">
                <input type="search" name="q" />
                <button type="submit">SEARCH</button>
            </form>
        </div>
        
        <div id="content">
            <h2>{{town.name}}, {{town.province}}</h2>
            <hr />
            
            The proud town of Mayor {{town.mayor.firstName}} {{town.mayor.lastName}}
            
            <ul>
                <li><a href="/prac/web/app_dev.php/town/evacuate/{{town.id}}">Evacuate Women & Children</a></li>
                <li><a href="/prac/web/app_dev.php/town/list-seniors/{{town.id}}">List Seniors</a></li>
                <li><a href="/prac/web/app_dev.php/town/list-pwds/{{town.id}}" title="People w/ Disabilities">
                        List PWDs
                </a></li>
            </ul>
        </div>
    </body>
</html>